-- Supabase本番DB向け差分SQL
-- 目的:
-- 1. title テーブルを作成する
-- 2. player に active_title_*_id を追加する
-- 3. 仮のSVG称号を削除し、PNGの3称号だけを残す
-- 4. player.title 参照用の外部キーを追加する

BEGIN;

CREATE TABLE IF NOT EXISTS public.title (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE,
    badge_filename varchar(255) NOT NULL,
    required_total_games integer DEFAULT 0,
    required_avg_rank double precision DEFAULT 4.1,
    required_win_count integer DEFAULT 0,
    required_last_avoidance_rate double precision DEFAULT 0,
    required_highest_rank_1_rate boolean DEFAULT false,
    required_highest_last_avoidance_rate boolean DEFAULT false,
    required_highest_raw_score_std_dev boolean DEFAULT false
);

ALTER TABLE public.player
    ADD COLUMN IF NOT EXISTS active_title_1_id integer,
    ADD COLUMN IF NOT EXISTS active_title_2_id integer,
    ADD COLUMN IF NOT EXISTS active_title_3_id integer;

INSERT INTO public.title (
    name,
    badge_filename,
    required_total_games,
    required_avg_rank,
    required_win_count,
    required_last_avoidance_rate,
    required_highest_rank_1_rate,
    required_highest_last_avoidance_rate,
    required_highest_raw_score_std_dev
)
VALUES
    (
        'トップチャンピオン',
        'top_champion.png',
        1,
        4.1,
        0,
        0,
        true,
        false,
        false
    ),
    (
        'ラス回避王',
        'last_dodging.png',
        1,
        4.1,
        0,
        0,
        false,
        true,
        false
    ),
    (
        '荒波の覇者',
        'standard_deviation.png',
        1,
        4.1,
        0,
        0,
        false,
        false,
        true
    )
ON CONFLICT (name) DO UPDATE SET
    badge_filename = EXCLUDED.badge_filename,
    required_total_games = EXCLUDED.required_total_games,
    required_avg_rank = EXCLUDED.required_avg_rank,
    required_win_count = EXCLUDED.required_win_count,
    required_last_avoidance_rate = EXCLUDED.required_last_avoidance_rate,
    required_highest_rank_1_rate = EXCLUDED.required_highest_rank_1_rate,
    required_highest_last_avoidance_rate = EXCLUDED.required_highest_last_avoidance_rate,
    required_highest_raw_score_std_dev = EXCLUDED.required_highest_raw_score_std_dev;

UPDATE public.player
SET
    active_title_1_id = CASE
        WHEN active_title_1_id IN (
            SELECT id FROM public.title WHERE name NOT IN ('トップチャンピオン', 'ラス回避王', '荒波の覇者')
        ) THEN NULL
        ELSE active_title_1_id
    END,
    active_title_2_id = CASE
        WHEN active_title_2_id IN (
            SELECT id FROM public.title WHERE name NOT IN ('トップチャンピオン', 'ラス回避王', '荒波の覇者')
        ) THEN NULL
        ELSE active_title_2_id
    END,
    active_title_3_id = CASE
        WHEN active_title_3_id IN (
            SELECT id FROM public.title WHERE name NOT IN ('トップチャンピオン', 'ラス回避王', '荒波の覇者')
        ) THEN NULL
        ELSE active_title_3_id
    END
WHERE
    active_title_1_id IN (
        SELECT id FROM public.title WHERE name NOT IN ('トップチャンピオン', 'ラス回避王', '荒波の覇者')
    )
    OR active_title_2_id IN (
        SELECT id FROM public.title WHERE name NOT IN ('トップチャンピオン', 'ラス回避王', '荒波の覇者')
    )
    OR active_title_3_id IN (
        SELECT id FROM public.title WHERE name NOT IN ('トップチャンピオン', 'ラス回避王', '荒波の覇者')
    );

DELETE FROM public.title
WHERE name NOT IN ('トップチャンピオン', 'ラス回避王', '荒波の覇者');

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'player_active_title_1_id_fkey'
          AND conrelid = 'public.player'::regclass
    ) THEN
        ALTER TABLE public.player
            ADD CONSTRAINT player_active_title_1_id_fkey
            FOREIGN KEY (active_title_1_id) REFERENCES public.title(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'player_active_title_2_id_fkey'
          AND conrelid = 'public.player'::regclass
    ) THEN
        ALTER TABLE public.player
            ADD CONSTRAINT player_active_title_2_id_fkey
            FOREIGN KEY (active_title_2_id) REFERENCES public.title(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'player_active_title_3_id_fkey'
          AND conrelid = 'public.player'::regclass
    ) THEN
        ALTER TABLE public.player
            ADD CONSTRAINT player_active_title_3_id_fkey
            FOREIGN KEY (active_title_3_id) REFERENCES public.title(id);
    END IF;
END $$;

COMMIT;