"""add title support

Revision ID: 7a001e4c1cd2
Revises: 6b1161ea1e80
Create Date: 2026-07-20 14:24:13.166329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a001e4c1cd2'
down_revision = '6b1161ea1e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_highest_rank_1_rate', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title', schema=None) as batch_op:
        batch_op.drop_column('required_highest_rank_1_rate')

    # ### end Alembic commands ###
