"""Add oka and uma columns to Game table

Revision ID: 8fc02df8e072
Revises: 
Create Date: 2025-07-06 18:41:16.363659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc02df8e072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oka', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uma1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uma2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uma3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uma4', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('uma4')
        batch_op.drop_column('uma3')
        batch_op.drop_column('uma2')
        batch_op.drop_column('uma1')
        batch_op.drop_column('oka')

    # ### end Alembic commands ###
