"""add avoidance and volatility titles

Revision ID: f889586b403b
Revises: 7a001e4c1cd2
Create Date: 2026-07-20 16:08:23.355690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f889586b403b'
down_revision = '7a001e4c1cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_highest_last_avoidance_rate', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('required_highest_raw_score_std_dev', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title', schema=None) as batch_op:
        batch_op.drop_column('required_highest_raw_score_std_dev')
        batch_op.drop_column('required_highest_last_avoidance_rate')

    # ### end Alembic commands ###
