"""add raw score fields

Revision ID: fb91e73a5159
Revises: c2d4e8a91f10
Create Date: 2026-07-23 02:19:15.358941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb91e73a5159'
down_revision = 'c2d4e8a91f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_total_raw_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('required_max_raw_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('required_min_raw_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('title', schema=None) as batch_op:
        batch_op.drop_column('required_min_raw_score')
        batch_op.drop_column('required_max_raw_score')
        batch_op.drop_column('required_total_raw_score')

    # ### end Alembic commands ###
